# Generated by Django 3.0.6 on 2020-05-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='in_tweet',
            new_name='tweet',
        ),
    ]
